[Interface]
# Device: Cute Zebra
PrivateKey = mBIXAQSAXdAMS4utyf5ygKLx4GKljWqcRB5+ce9XZWQ=
Address = 10.65.158.193/32
DNS = 10.64.0.1

[Peer]
PublicKey = xpKhRTf9JI269S2PujLbrJm1TwIe67HD5CLe+sP4tUU=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 146.70.124.130:51820