[Interface]
# Device: Nice Squid
PrivateKey = EOHdqVS1cltl/eYnk44GuKEmEAiHjhBIACo+srb1y0I=
Address = 10.66.197.209/32
DNS = 10.64.0.1

[Peer]
PublicKey = PJvsgLogdAgZiVSxwTDyk9ri02mLZGuElklHShIjDGM=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 154.47.29.2:51820