[Interface]
# Device: Caring Kitten
PrivateKey = wL9ntwcSH13n9QSG7RaAL8K2t65dWAZK2afIVn2a4VQ=
Address = 10.67.167.58/32
DNS = 10.64.0.1

[Peer]
PublicKey = Ekc3+qU88FuMfkEMyLlgRqDYv+WHJvUsfOMI/C0ydE4=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 146.70.124.194:51820