version: '3.8'

services:

  ### --- VPN & Download Stack --- ###

  vpn:
    image: haugene/transmission-openvpn
    container_name: vpn
    env_file: .env
    cap_add:
      - NET_ADMIN
    security_opt:
      - label=disable
    devices:
      - /dev/net/tun
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - KILL_SWITCH=on
      - UFW_ALLOW_GW_NET=true
      - VPN_DISABLE_IPV6=true
    ports:
      - 9091:9091 # Transmission Web UI
      - 8112:8112 # Deluge Web UI
    volumes:
      - ./config/vpn:/config/vpn
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/media/extra/downloads:/mnt/media/extra/downloads
      - ${ROOT}/config/deluge:/config
    depends_on:
      - vpn
    restart: always

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9117:9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads
      - ${ROOT}/config/jackett:/config
    restart: unless-stopped

  ### --- Media Server --- ###

  plex-server:
    image: plexinc/pms-docker:latest
    container_name: plex-server
    network_mode: host
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT}/config/plex/db:/config
      - ${ROOT}/config/plex/transcode:/transcode
      - /mnt/media:/mnt/media
      - /mnt/media/extra:/mnt/media/extra
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/extra:/mnt/media/extra
      - /mnt/media/downloads:/mnt/media/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/extra:/mnt/media/extra
      - /mnt/media/downloads:/mnt/media/downloads
    restart: unless-stopped

  ### --- Web Reverse Proxy (NGINX) --- ###

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/proxy/logs:/var/log/nginx
      - ${ROOT}/config/nginx/Plexconf:/etc/nginx/conf.d
      - ${ROOT}/config/nginx/SSL_certificate:/etc/nginx/SSL_certificate
      - ${ROOT}/config/nginx/letsencrypt/live:/etc/letsencrypt/live
      - ${ROOT}/config/nginx/letsencrypt/archive:/etc/letsencrypt/archive
      - ${ROOT}/config/nginx/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    restart: unless-stopped

  ### --- Monitoring Stack --- ###

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${ROOT}/config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ${ROOT}/config/grafana:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    restart: unless-stopped

  ping-exporter:
    image: czerwonk/ping_exporter
    container_name: ping-exporter
    command:
      - '--ping.interval=30s'
      - '--ping.targets=192.168.1.1,192.168.3.1,1.1.1.1'
    ports:
      - "9427:9427"
    networks:
      - monitoring
    restart: unless-stopped

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ${ROOT}/config/snmp:/etc/snmp_exporter
    networks:
      - monitoring
    restart: unless-stopped

  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    ports:
      - "9798:9798"
    networks:
      - monitoring
    restart: unless-stopped
networks:
  monitoring:


volumes:
  prometheus-data:
  grafana-storage:
