global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'plex'
    static_configs:
      - targets: ['plex-exporter:9000']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

